### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: 67 with broken AST

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#106]
`a.sadl`:
```java
 uri "http://sadl.org/a.sadl".
 AAA is a class.
```

`d1.dailog`:
```
 uri "http://sadl.org/d1.dialog".
 import "http://sadl.org/a.sadl" // <- note the missing EOL here
```

Error:
```
ENTRY org.apache.log4j 4 0 2020-04-20 09:34:16.196
!MESSAGE org.eclipse.xtext.validation.ResourceValidatorImpl  - String index out of range: 67

!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 67
	at java.lang.String.substring(String.java:1963)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.storeOriginalElementInfo(JenaBasedDialogModelProcessor.java:470)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.onValidate(JenaBasedDialogModelProcessor.java:343)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by crapo** [comment]
fixed
