### ISSUE TITLE
BadLocationException when saving the Dialog editor. The AST is valid, all links are resolved

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#110]
Model:
```
 uri "http://sadl.org/demo2b.dialog" alias demo2b.
 
import "http://aske.ge.com/metamodel".
import "http://aske.ge.com/hypersonicsV2".
import "http://aske.ge.com/turbo".

TotalThrust is a type of UnittedQuantity.
totalThrust describes Aircraft with values of type TotalThrust.

what is totalThrust of an Aircraft when engine of the Aircraft is a CF6 and numEngines is 2 and the altitude is 32000 ft and the speed is 700 mph?


// <--- note the empty lines here
```

Error:
```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.get(AbstractDocument.java:968)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.checkForAdditionalNewlines(DialogAnswerProvider.java:446)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.generateInsertionLocation(DialogAnswerProvider.java:578)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.lambda$2(DialogAnswerProvider.java:318)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3793)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by kittaakos** [comment]
I cannot reproduce it consistently 😕

**Comment by kittaakos** [comment]
> I cannot reproduce it consistently 😕

It has to do something with the undo-stack; happens when I do <kbd>⌘</kbd>+<kbd>Z</kbd>(`undo`) in the editor. Unfortunately, I am still unable to consistently reproduce the defect.

**Comment by crapo** [comment]
I think it has to do with using EMF Resource rather than URI to store dialog widow content. I'm fixing in MissingPatterns branch of sadlos2

**Comment by crapo** [comment]
I think this is resolved with the update to use URI, pushed to sadlos2 MissingPatterns and ASKE TA1 CodeExtraction branches.
