### ISSUE TITLE
[releng] Remove the `.target` project

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#13]
It is unused and was removed once as part of #4.
See here: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/4/files#diff-9730dbf76d5c0426033f370fc57f9754L1

**Comment by crapo** [comment]
@kittaakos , so what do you mean by "I hope it will work, but Dialog does not belong here." I hope you just mean that it's the wrong repo on github for the issue, not that Dialog isn't going to work imported into Eclipse-2020-03. Do you expect that I need to do anything to make it work?

**Comment by kittaakos** [comment]
> mean that it's the wrong repo

Yes. I have a hard time following the requirements if I get a GitHub notification from `sadlos2` but you want to do something with Dialog.

> not that Dialog isn't going to work

It should work, I did it several times.

> Do you expect that I need to do anything to make it work?

No.

**Comment by crapo** [comment]
Here's what I've done:
1. Cloned DARPA-ASKE-TA1 repo
2. Imported as existing maven projects (forgot to do mvn install first)
3. Deleted projects and did mvn clean install
4. mvn install failed:
15634 [org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main()] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - org/eclipse/emf/mwe2/ecore/CvsIdFilteringGeneratorAdapterFactoryDescriptor
java.lang.NoClassDefFoundError: org/eclipse/emf/mwe2/ecore/CvsIdFilteringGeneratorAdapterFactoryDescriptor
        at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.doGenerate(EMFGeneratorFragment2.java:1010)
        at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.generate(EMFGeneratorFragment2.java:469)
        at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:50)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:230)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:132)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:34)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:212)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:37)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.mwe2.ecore.CvsIdFilteringGeneratorAdapterFactoryDescriptor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more

**Comment by crapo** [comment]
@kittaakos , can you help me get Dialog working with Eclipse-2020-03?

**Comment by kittaakos** [comment]
> can you help me get Dialog working with Eclipse-2020-03?

Yes, please send the link.

**Comment by crapo** [comment]
@kittaakos , what was the git bash cmd line inclusion to set the proxy? I can't seem to find it anywhere.

**Comment by kittaakos** [comment]
> to set the proxy

We used it to bypass, unset the proxy. Did you mean this? https://stackoverflow.com/questions/41439747/how-to-bypass-the-http-proxy-that-i-have-set-using-git-config

**Comment by crapo** [comment]
Yes, thanks!! I couldn't find that by googling to save me.
