### ISSUE TITLE
Abstract Dialog Test class

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#23]
I need the capability to convert a .dialog file into an OWL file using the JenaBasedDialogModelProcessor from a JUnit test. For SADL, this is accomplished through calls to assertValidatesTo in AbstractSadlTest. I don't know the easiest/best way to so this for DIALOG files. I suspect that you, @kittaakos , could pretty quickly provide this capability? In a fraction of the time it would take me to figure out how to accomplish it. This is need to provide end-to-end JUnit tests/standalone demos.

**Comment by kittaakos** [comment]
@crapo, can you please share one or two valid `.dialog` files? It is up to you whether it is a text copy-pasted here or a zip file attached to GitHub. I try to finish the implementation either today or tomorrow.

**Comment by crapo** [comment]
Attaching an exported project zip file with several .dialog files. "demo.dialog", "test.dialog" are examples.
[M5.zip](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/files/3591646/M5.zip)

**Comment by kittaakos** [comment]
I cannot build it. SADL, as of today from the `development` branch, has `3.2.1-SNAPSHOT` version. DARPA requires `3.2.0-SNAPSHOT` from the target platform. Which SADL branch should I use? Please note, I had to wipe my local Maven cache, I do not have SADL `3.2.0` available there.

Local Maven:
```
Akoss-MacBook-Pro:com.ge.research.sadl akos.kitta$ pwd
/Users/akos.kitta/.m2/repository/com/ge/research/sadl/com.ge.research.sadl
Akoss-MacBook-Pro:com.ge.research.sadl akos.kitta$ ls -al
total 8
drwxr-xr-x   4 akos.kitta  staff   128 Sep 10 08:31 .
drwxr-xr-x  32 akos.kitta  staff  1024 Sep 10 08:33 ..
drwxr-xr-x   8 akos.kitta  staff   256 Sep 10 08:31 3.2.1-SNAPSHOT
-rw-r--r--   1 akos.kitta  staff   300 Sep 10 08:31 maven-metadata-local.xml
Akoss-MacBook-Pro:com.ge.research.sadl akos.kitta$ 
```

Error:
```
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.ge.research.sadl:com.ge.research.sadl.target:target:3.2.0-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.ge.research.sadl:com.ge.research.sadl.target:target:3.2.0-SNAPSHOT
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:122)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact com.ge.research.sadl:com.ge.research.sadl.target:target:3.2.0-SNAPSHOT
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact (DefaultTargetPlatformConfigurationReader.java:389)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget (DefaultTargetPlatformConfigurationReader.java:342)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration (DefaultTargetPlatformConfigurationReader.java:75)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject (DefaultTychoResolver.java:87)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:90)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:267)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by kittaakos** [comment]
> Which SADL branch should I use?

`AugmentedTypes` seems to work. I am down to one test failure. For this task, I will ignore the test.

```
Results :

Tests in error: 
  TestSadlServerMD_Mobius.testWithJenaReasoner:75 » NamedServiceNotFound Service...

Tests run: 9, Failures: 0, Errors: 1, Skipped: 2
```

**Comment by kittaakos** [comment]
I still cannot compile. How do you set up DARPA with SADL source? Thanks!

```
java.lang.RuntimeException: Problems running workflow com.ge.research.sadl.darpa.aske.GenerateDialog: org.eclipse.emf.ecore.xmi.IllegalValueException: Value '2.16' is not legal. (platform:/resource/com.ge.research.sadl/model/generated/SADL.genmodel, 6, 73)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:104)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.IllegalValueException: Value '2.16' is not legal. (platform:/resource/com.ge.research.sadl/model/generated/SADL.genmodel, 6, 73)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
	at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.loadResource(XtextGeneratorResourceSetInitializer.java:51)
	at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.lambda$initialize$0(XtextGeneratorResourceSetInitializer.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.initialize(XtextGeneratorResourceSetInitializer.java:43)
	at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:218)
	at org.eclipse.xtext.xtext.generator.StandardLanguage.initialize(StandardLanguage.java:189)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:185)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:139)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:21)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:65)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:197)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:29)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:18)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
	... 4 more
Caused by: org.eclipse.emf.ecore.xmi.IllegalValueException: Value '2.16' is not legal. (platform:/resource/com.ge.research.sadl/model/generated/SADL.genmodel, 6, 73)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.setFeatureValue(XMLHandler.java:2715)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.setAttribValue(XMLHandler.java:2769)
	at org.eclipse.emf.ecore.xmi.impl.SAXXMIHandler.handleObjectAttribs(SAXXMIHandler.java:79)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectFromFactory(XMLHandler.java:2247)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1384)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1522)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1044)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:78)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1359)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1289)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 19 more
Caused by: java.lang.IllegalArgumentException: The value '2.16' is not a valid enumerator of 'GenRuntimeVersion'
	at org.eclipse.emf.codegen.ecore.genmodel.impl.GenModelFactoryImpl.createGenRuntimeVersionFromString(GenModelFactoryImpl.java:406)
	at org.eclipse.emf.codegen.ecore.genmodel.impl.GenModelFactoryImpl.createFromString(GenModelFactoryImpl.java:114)
	at org.eclipse.emf.ecore.xmi.impl.XMLHelperImpl.createFromString(XMLHelperImpl.java:1615)
	at org.eclipse.emf.ecore.xmi.impl.XMLHelperImpl.setValue(XMLHelperImpl.java:1156)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.setFeatureValue(XMLHandler.java:2710)
	... 49 more
```

**Comment by crapo** [comment]
I'm sorry I didn't specify AugmentedTypes. That is the correct branch for sadl, master branch for ASKE TA1. I do not have any compile issues and don't recall seeing an issue like this. Can we do a quick Skype meeting to discuss/look at my environment?

**Comment by crapo** [comment]
TestSadlServerMD_Mobius.testWithJenaReasoner is already ignored in master branch. Not sure why it ran for you....

**Comment by kittaakos** [comment]
> Can we do a quick Skype meeting to discuss/look at my environment?

I have fixed it locally, thank you! The duplicate target platform files were confusing. See here: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/13

I am down to two compiler errors:

![Screen Shot 2019-09-10 at 15 11 42](https://user-images.githubusercontent.com/1405703/64616667-4d528e80-d3dd-11e9-8892-78636b2f60a9.jpg)

Are you sure you have pushed everything to the remote `AugmentedTypes` branch in SADL and `master` in DARPA?

**Comment by crapo** [comment]
isAstSyntaxValid is in SadlModelProcessor and was updated in AugmentedTypes 11 days ago.
replaceFileExtension is a static method in SadlUtils and was also pushed 11 days ago.

**Comment by crapo** [comment]
Not sure I understand. There is a .target file somewhere where there shouldn't be one? Where?

**Comment by kittaakos** [comment]
> was also pushed 11 days ago

I will check, thank you!

> There is a .target file

The entire `com.ge.research.sadl.darpa.aske.dialog.target` is obsolete. We have to use the target platform file from SADL anyway.

**Comment by kittaakos** [comment]
@crapo, I resolved all compiler errors locally. Thank you for your support!

> to convert a .dialog file into an OWL file
> this is accomplished through calls to assertValidatesTo in AbstractSadlTest

This is not true. `assertValidatesTo` is an end-to-end test, it runs the validation, you can assert the ontology model, the rules, and commands, but it does not generate anything. What do you need, the generated OWL file or just the same functionality as the `assertValidatesTo ` provides for SADL but with `.dialog` models?

**Comment by crapo** [comment]
I need the generated OWL file.

**Comment by kittaakos** [comment]
> I need the generated OWL file

I see. It is not trivial. All of our tests run without any files, they won't generate anything at all. I try to figure out something.

**Comment by crapo** [comment]
Ah, I missed this subtlety. I don't need an OWL file, I just need the in-memory OntModel created by the model processor.

**Comment by kittaakos** [comment]
> I just need the in-memory OntModel created by the model processor.

OK, it simplifies a lot. I try to finish this today to avoid blocking you.

**Comment by crapo** [comment]
Thanks!!

**Comment by crapo** [comment]
@kittaakos , can you use the attached simple project to set up a test that shows how to use this?

[SimpleDialog.ZIP](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/files/3601473/SimpleDialog.ZIP)

**Comment by crapo** [comment]
@kittaakos , I checked out the dialog-test branch and made some corrections and pushed results. There is one update to sadl AugmentedTypes branch that supports this. Now there are no errors in Dialog model processing until we get to the inferencing part. I was surprised to see that the sadl tests do not appear to do any actual inferencing. Inferencing is only actually tested in sadl.ui tests. The issue is that inferencing seems to rely on there actually being a model folder, which only exists in the sadl.ui tests. I suppose the implication is that we need to extend testing to a dialog.ui test set where we can actually do inferencing. But the current fixes seems to handle everything short of inferencing.

**Comment by crapo** [comment]
@kittaakos , I think there must be a project configuration issue, class loader related, because using reflection to find the class "com.ge.research.sadl.jena.translator.JenaTranslatorPlugin" fails in the configuration manager. If you know what that might be please let me know. Otherwise I'll look for differences with the sadl.test project.

**Comment by crapo** [comment]
@kittaakos , I've added a test testGetTranslatorInstance to DialogTest and an identical test to SadlJenaOSTest in sadl.test project. Both illustrate the issue that the class loader is unable to find the class com.ge.research.sadl.jena.translator.JenaTranslatorPlugin. If this were resolved we might be able to get inference testing to work from backend (headless) tests. Any ideas?

**Comment by crapo** [comment]
@kittaakos , I bit the bullet and modified the reasoner so that it will work without a model folder or any files. That will greatly facilitate all testing of inference, both sadl and dialog. At the moment I don't think there are any critical issues.

**Comment by crapo** [comment]
I have merged your dialog-test branch into master. Note that there are some tests that will fail for you as they depend on REST services that are internal.

**Comment by kittaakos** [comment]
> I was surprised to see that the sadl tests do not appear to do any actual inferencing. Inferencing is only actually tested in sadl.ui tests.

Yes. Inferencing always relied on the FS and expected a certain folder structure.

> I suppose the implication is that we need to extend testing to a dialog.ui

You expected a JUnit test, please see the [original issue description](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/23#issue-491107394):
 > This is need to provide end-to-end JUnit tests/standalone demos.

> But the current fixes seems to handle everything short of inferencing.

Great! I am looking into it.

> I have merged your dialog-test branch into master.

No, you did not. You have merged the `master` into the `dialog-test` branch. Anyway, I will continue on the work on the `dialog-test`.

> Note that there are some tests that will fail for you as they depend on REST services that are internal.

OK, thanks for the note.

**Comment by kittaakos** [comment]
> class loader related, because using reflection to find the class "com.ge.research.sadl.jena.translator.JenaTranslatorPlugin"

Are you referring to this error?
```
java.lang.ClassNotFoundException: Cannot find service class for name: com.ge.research.sadl.jena.translator.JenaTranslatorPlugin for service API interface com.ge.research.sadl.reasoner.ITranslator.
	at com.ge.research.sadl.reasoner.ConfigurationManager.getClassInstance(ConfigurationManager.java:662)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslatorInstanceByClass(ConfigurationManager.java:559)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslatorInstance(ConfigurationManager.java:553)
	at com.ge.research.sadl.reasoner.ConfigurationManager.initializeTranslator(ConfigurationManager.java:517)
	at com.ge.research.sadl.reasoner.ConfigurationManager.getTranslator(ConfigurationManager.java:344)
	at com.ge.research.sadl.darpa.aske.tests.DialogTest.testGetTranslatorInstance(DialogTest.java:779)
```

**Comment by kittaakos** [comment]
> Are you referring to this error?

Here is the fix in SADL: https://github.com/crapo/sadlos2/pull/382

**Comment by kittaakos** [comment]
I have fixed a few things. The most importand part was the missing registration of the model processor and the inferencer for the dialog grammar. Otherwise, the Java SPI does not work.
I have enabled two tests, they're green. See the PR: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/27

**Comment by kittaakos** [comment]
The rest of this task seems to be covered by #28. I propose closing this issue.

**Comment by crapo** [comment]
I agree, closing this issue.
