### ISSUE TITLE
Proper insertion into dialog window and cursor relocation

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#34]
addCurationManagerContentToDialog in DialogAnswerProvider throws exceptions and doesn't allow new text at end to be scrolled. Also, would be nice to relocate cursor to end of insertion.

**Comment by crapo** [comment]
With the current code on master branch, I get this kind of error when inserting into the Dialog window document.

!ENTRY org.eclipse.text 4 2 2019-09-19 12:01:37.990
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.text".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.custom.StyledText.getLinePixel(StyledText.java:4249)
	at org.eclipse.swt.custom.StyledText.handleTextChanging(StyledText.java:6381)
	at org.eclipse.swt.custom.StyledText$5.textChanging(StyledText.java:5743)
	at org.eclipse.jface.text.DefaultDocumentAdapter.fireTextChanging(DefaultDocumentAdapter.java:370)
	at org.eclipse.jface.text.DefaultDocumentAdapter.documentAboutToBeChanged(DefaultDocumentAdapter.java:287)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentAboutToBeChanged(AbstractDocument.java:636)
	at org.eclipse.jface.text.AbstractDocument.set(AbstractDocument.java:1136)
	at org.eclipse.jface.text.AbstractDocument.set(AbstractDocument.java:1128)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.addCurationManagerContentToDialog(DialogAnswerProvider.java:827)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.initiateMixedInitiativeInteraction(DialogAnswerProvider.java:916)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.addCurationManagerInitiatedContent(DialogAnswerProvider.java:863)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.notifyUser(AnswerCurationManager.java:1063)
	at com.ge.research.sadl.darpa.aske.processing.imports.JavaModelExtractorJP.parse(JavaModelExtractorJP.java:171)
	at com.ge.research.sadl.darpa.aske.processing.imports.JavaModelExtractorJP.process(JavaModelExtractorJP.java:163)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processImports(AnswerCurationManager.java:284)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaImportOperation.importFiles(JavaImportOperation.java:799)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaImportOperation.importFileSystemObjects(JavaImportOperation.java:966)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaImportOperation.execute(JavaImportOperation.java:461)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.eclipse.text 4 2 2019-09-19 12:01:38.425
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.text".
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.ui.internal.texteditor.quickdiff.DocumentLineDiffer.handleChanged(DocumentLineDiffer.java:919)
	at org.eclipse.ui.internal.texteditor.quickdiff.DocumentLineDiffer.documentChanged(DocumentLineDiffer.java:859)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:747)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:716)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:700)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:774)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.access$9(XtextDocument.java:1)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$3.run(XtextDocument.java:713)
	at org.eclipse.xtext.ui.util.DisplayRunnable$1.run(DisplayRunnable.java:25)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:168)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:372)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:977)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaFileResourceImportPage1.executeOwlImportOperation(JavaFileResourceImportPage1.java:473)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaFileResourceImportPage1.importResources(JavaFileResourceImportPage1.java:742)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaFileResourceImportPage1.finish(JavaFileResourceImportPage1.java:515)
	at com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaFileImportWizard.performFinish(JavaFileImportWizard.java:83)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:775)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:414)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:161)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:293)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:403)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:154)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by kittaakos** [comment]
Thanks for logging. It is a little bit unrelated. See the stack-trace; it happens after the Java import part. I am sure we can fix it.

```
com.ge.research.sadl.darpa.aske.ui.answer.imports.JavaFileImportWizard.performFinish(JavaFileImportWizard.java:83)
```

**Comment by crapo** [comment]
This example is called from Java import wizard, but it goes through the same code and I think gives the same error as when inserted from elsewhere, at least sometimes.

**Comment by kittaakos** [comment]
> but it goes through the same code

Sure, but the wizard's `performFinish` runs in a different thread the main, UI thread. It is called: `ModalContext$ModalContextThread`, that's why you see the `Invalid thread access` error. Long story short: I am going to fix this issue, but I do not think other `document` updates have the same problem.

> at least sometimes.

Well if you know how to reproduce it outside of the Java import wizard consistently, please let me know and I fix those issues too. 😊

**Comment by crapo** [comment]
@kittaakos , I pushed fix to file naming bug. Can't fully test because I end up with a console provider because I don't have your new code.

**Comment by kittaakos** [comment]
> I pushed fix to file naming bug

Thank you!

**Comment by kittaakos** [comment]
> Also, would be nice to relocate cursor to end of insertion.

This is already available from the `master`:

![screencast 2019-10-07 15-03-41](https://user-images.githubusercontent.com/1405703/66314242-08564500-e914-11e9-8a48-f91bad13923e.gif)
