### ISSUE TITLE
Error: Unhandled condition: triple has a null element.

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#40]
`Model.sadl`:
```
 uri "http://sadl.org/Model.sadl" alias mdl.
 
 Mass is a type of UnittedQuantity, 
 	described by force with values of type Force,
 	described by speed with values of type Speed,
 	described by acceleration with values of type Acceleration.
 
 Force is a type of UnittedQuantity.
 Speed is a type of UnittedQuantity.
 Acceleration is a type of UnittedQuantity.
 
 External secondLaw(double m, double acc) returns double: "http://sadl.org/secondlaw".

```

`SaveTarget.sadl`:
```
uri "http://sadl.org/SaveTarget.sadl" alias svtgt.
```

`x.dialog`:
```
uri "http://sadl.org/x.dialog".
import "http://sadl.org/Model.sadl".
 
target model "http://sadl.org/SaveTarget.sadl" alias tgt.

MyHulk is a Mass with ^value 280, with unit "lbs".

What is the force of some Mass when the acceleration of the Mass is 25?
```

The problematic question is:
```
What is the force of some Mass when the acceleration of the Mass is 25?
```

```
12130 [Worker-3: Building workspace] ERROR org.eclipse.xtext.validation.ResourceValidatorImpl  - 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.ge.research.sadl.reasoner.ResultSet.<init>(ResultSet.java:48)
	at com.ge.research.sadl.jena.JenaBasedSadlInferenceProcessor.insertTriplesAndQuery(JenaBasedSadlInferenceProcessor.java:1718)
	at com.ge.research.sadl.darpa.aske.inference.JenaBasedDialogInferenceProcessor.insertTriplesAndQuery(JenaBasedDialogInferenceProcessor.java:602)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.insertTriplesAndQuery(AnswerCurationManager.java:2239)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processWhatIsContent(AnswerCurationManager.java:1654)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processUserRequest(AnswerCurationManager.java:1435)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processConversation(AnswerCurationManager.java:2399)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.onValidate(JenaBasedDialogModelProcessor.java:443)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:60)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:46)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:93)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:63)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:82)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:288)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:268)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:162)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by crapo** [comment]
Although this will not work without the Web services for the computational graph, I believe that the error you report is fixed in yesterday's pushes.

**Comment by kittaakos** [comment]
> is fixed in yesterday's pushes.

I can confirm. I have rebased from the `master`, and now I can see the error is handled gracefully in the editor; I can see `CM: "Failed to evaluate answer".`.

I am closing this as fixed.
