### ISSUE TITLE
NPE on dialog file reopen

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#51]
@kittaakos , I don't expect that you can reproduce without services running, but when we run a query that inserts an importing as well as a response into the Dialog window, then close the window without saving  and reopen, then do another action that results in additions to the Dialog window we get the error below, MAC or Windows. Maybe we can have a meeting to look at tomorrow?

`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.notifyUser(AnswerCurationManager.java:1539)
	at com.ge.research.sadl.darpa.aske.inference.JenaBasedDialogInferenceProcessor.insertTriplesAndQuery(JenaBasedDialogInferenceProcessor.java:1175)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.insertTriplesAndQuery(AnswerCurationManager.java:2713)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processWhatIsContent(AnswerCurationManager.java:2020)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processUserRequest(AnswerCurationManager.java:1801)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processConversation(AnswerCurationManager.java:2873)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.onValidate(JenaBasedDialogModelProcessor.java:444)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.ge.research.sadl.darpa.aske.ui.answer.GetResourceUri.exec(GetResourceUri.java:16)
	at com.ge.research.sadl.darpa.aske.ui.answer.GetResourceUri.exec(GetResourceUri.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.addCurationManagerContentToDialog(DialogAnswerProvider.java:302)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.addCurationManagerContentToDialog(DialogAnswerProvider.java:295)
	at com.ge.research.sadl.darpa.aske.ui.answer.DialogAnswerProvider.addCurationManagerInitiatedContent(DialogAnswerProvider.java:453)
	... 27 more
`

**Comment by kittaakos** [comment]
I have [drafted a PR](https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/52) with a few changes, but I cannot reproduce the issue by simply uncommenting any of the questions from the following file:

```
uri "http://aske.ge.com/demodiag" alias demodiag.

import "http://aske.ge.com/metamodel".
import "http://aske.ge.com/hypersonicsV2".
import "http://aske.ge.com/dbnnodes".

//what is the totalTemperature of some Air when the altitude of the Air is 38000 ft?

//what is the totalTemperature of some Air when the altitude of the Air is 11500 m?
```

@crapo, I have seen the issue on Alfredo's mac, but I cannot reproduce it locally. How can I have the same environment as you? Thanks!

**Comment by kittaakos** [comment]
I have imported the project from here: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/45#issue-507993493

**Comment by agabaldon** [comment]
Andy's environment uses a local version of the services I mentioned in the email. I checked if I could reproduce the issue using simple queries that don't need those services but couldn't. Thanks.

**Comment by kittaakos** [comment]
> but couldn't.

Does the insertion error occur if you temporarily disable the graph generation?

**Comment by crapo** [comment]
I also had confirmed that I can't reproduce the error if only doing "simple queries".

**Comment by agabaldon** [comment]
@kittaakos No it doesn't, so you're right, it has to do with that. As you're aware, one of the last changes from yesterday got rid of the NPE, but now the answers don't get added in the dialog page when querying after reopening the dialog page.

**Comment by kittaakos** [comment]
> No it doesn't, so you're right, it has to do with that.

This is just a guess; the graphs are opened up in the default browser inside Eclipse, which is platform dependent.

**Comment by agabaldon** [comment]
Right. Changing it to open the graphs on an external browser yields the same result, at least on my setup.
