### ISSUE TITLE
DialogTest test cases pass in Eclipse but fail when run from Maven

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#59]
@kittaakos , my Maven builds fail with failing tests, but the same tests succeed when run in Eclipse. Is this reproducible?

**Comment by crapo** [comment]
Most of the errors are of the form:
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.424 s <<< FAILURE! - in com.ge.research.sadl.darpa.aske.tests.BasicMissingPatternsInCompareTest
test  Time elapsed: 0.727 s  <<< ERROR!
org.eclipse.emf.common.util.WrappedException: java.lang.IllegalArgumentException: Expected a `platform:/resource/` URI. Got instead: synthetic://test/SadlImplicitModel.sadl.
	at com.ge.research.sadl.darpa.aske.tests.BasicMissingPatternsInCompareTest.test(BasicMissingPatternsInCompareTest.java:50)
Caused by: java.lang.IllegalArgumentException: Expected a `platform:/resource/` URI. Got instead: synthetic://test/SadlImplicitModel.sadl.
	at com.ge.research.sadl.darpa.aske.tests.BasicMissingPatternsInCompareTest.test(BasicMissingPatternsInCompareTest.java:50)

While one is:
com.ge.research.sadl.reasoner.ConfigurationException: Translator class 'com.ge.research.sadl.jena.translator.JenaTranslatorPlugin' not found
	at com.ge.research.sadl.darpa.aske.tests.DialogTest.testGetTranslatorInstance(DialogTest.java:2663)
Caused by: java.lang.ClassNotFoundException: Cannot find service class for name: com.ge.research.sadl.jena.translator.JenaTranslatorPlugin for service API interface com.ge.research.sadl.reasoner.ITranslator.
	at com.ge.research.sadl.darpa.aske.tests.DialogTest.testGetTranslatorInstance(DialogTest.java:2663)

**Comment by kittaakos** [comment]
> but the same tests succeed when run in Eclipse

It fails on my side from Eclipse too:
```
Rule R1:  if is(mdl:sfc,0.35) then is(mdl:thrust,2000).
1    [main] ERROR xt.validation.ResourceValidatorImpl  - 0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processResultsOfInsertRulesAndQuery(AnswerCurationManager.java:3012)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processCompareRequest(AnswerCurationManager.java:2665)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processUserRequest(AnswerCurationManager.java:2651)
	at com.ge.research.sadl.darpa.aske.curation.AnswerCurationManager.processConversation(AnswerCurationManager.java:3813)
	at com.ge.research.sadl.darpa.aske.processing.JenaBasedDialogModelProcessor.onValidate(JenaBasedDialogModelProcessor.java:463)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:75)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:71)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:55)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at com.ge.research.sadl.tests.SadlTestAssertions.assertValidatesTo(SadlTestAssertions.java:55)
	at com.ge.research.sadl.darpa.aske.tests.AbstractDialogTest.assertValidatesTo(AbstractDialogTest.java:42)
	at com.ge.research.sadl.darpa.aske.tests.BasicMissingPatternsInCompareTest.test(BasicMissingPatternsInCompareTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

Which branch should I use?
 - I was on `development` in SADL: https://github.com/crapo/sadlos2/commit/c03a0f3b
 - And `master` in `Dialog`: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/commit/9b153b8

**Comment by crapo** [comment]
Sorry I didn't say. MissingPatterns for SADL and master for Dialog.

**Comment by kittaakos** [comment]
> Sorry I didn't say. MissingPatterns for SADL and master for Dialog.

:+1: Checking.

**Comment by kittaakos** [comment]
It's fixed: https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/pull/65
